In [1]:
#%reload_ext Cython

In [2]:
#import typing
#import copy
#import pdb
#from IPython.display import clear_output
#import numpy as np
#import time
#from colorama import Fore
#import sys
#import cProfile
#from multiprocessing import Pool
#import chess 
#import chess.uci
#import tensorflow as tf
#import random
#import boardclass
import test
import boardclass

In [3]:
path = "../extracted/good_games.txt"
tested_upto = 118
#boardclass.file_to_move_lists(path,move_size=5)
troubling_moves,troubling_index = test.compare_boards_with_file(path,index=tested_upto)
print(troubling_moves)
print(troubling_index)

118 of of 29168
119 of of 29168
my board
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0]
 [ 0  0  0  0  6  0  0  0]
 [ 0  6  0  0 -6  6  6  6]
 [ 0  0  0  0 -5  0  0  0]
 [ 0  0 -6  0  0  0  0  0]
 [ 0  0  0  0  0  0 -6  0]
 [ 0  0  0  0  0  0  0  0]]
ground truth
. . . . . . . .
. . . . k . . .
. . . . p P . .
. p . . . . p p
. . . . K . . .
. . P . . . . .
. . . . . . P .
. . . . . . . .
At 2, 5, expected -6, got 0. Previous moves: ['e4e5', 'f6d5', 'f3d5', 'b7d5', 'g3e4', 'd5e4', 'd4e4', 'h6h5', 'c2c3', 'f7f5'], reached 70 out of 78. Move is e5f6
['d2d4', 'd7d5', 'b1c3', 'e7e6', 'c1f4', 'f8d6', 'f4g3', 'g8f6', 'd1d3', 'a7a6', 'f2f3', 'c7c5', 'e2e4', 'c5d4', 'd3d4', 'd6g3', 'h2g3', 'd5e4', 'd4d8', 'e8d8', 'e1c1', 'd8e7', 'f3e4', 'b8c6', 'f1e2', 'b7b5', 'g3g4', 'g7g5', 'e2f3', 'c8b7', 'g1e2', 'h7h6', 'e2g3', 'c6e5', 'd1d2', 'a8d8', 'h1d1', 'd8d2', 'd1d2', 'h8d8', 'd2d8', 'e7d8', 'a2a3', 'd8e7', 'c1d2', 'e5g4', 'c3e2', 'g4e5', 'd2e3', 'e5c4', 'e3d4', 'c4b2', 'e2c3', 'b2c4', 'a3a4'

In [4]:
test.start_game(-1,troubling_moves,watching=True,fast_play=True,fast_play_count=troubling_index,clear=True,set_pdb=True)

8	_	_	_	_	_	_	_	_	

7	_	_	_	_	King	_	_	_	

6	_	_	_	_	Pawn	_	_	_	

5	_	Pawn	_	_	Pawn	Pawn	Pawn	Pawn	

4	_	_	_	_	King	_	_	_	

3	_	_	Pawn	_	_	_	_	_	

2	_	_	_	_	_	_	Pawn	_	

1	_	_	_	_	_	_	_	_	

	a	b	c	d	e	f	g	h	did not make move


KeyboardInterrupt: 